



[[sec_5]]
== ASSURANCE LEVELS

.ARTICLE 54 REFERENCE
____
*Article 54. A European cybersecurity certification scheme shall include
at least the following elements:*

(d) where applicable, one or more assurance levels;
____

The scheme defines three assurance levels, with assurance level Basic
corresponding to the 'basic' assurance level of the EUCSA, assurance
level Substantial corresponding to the 'substantial' assurance level
of the EUCSA, and assurance level High corresponding to the 'high'
assurance level of the EUCSA.

As specified in the EUCSA's Article 52(5), assurance level Basic is
"intended to minimise the known basic risks of incidents and cyberattacks"
and can be further defined as follows:

* Assurance level Basic should provide limited assurance that the
cloud service is built and operated with procedures and mechanisms
to meet the corresponding security requirements at a level intended
to minimize the known basic risks of incidents and cyberattacks.

* Assurance level Basic should be suitable for cloud services that
are designed to meet typical security requirements on services for
non-critical data and systems.

* The typical attacker profile for assurance level Basic should be
a single person with limited skills repeating a known attack with
limited resources, not including the ability to perform social engineering
attacks.

* The evaluation scope for assurance level Basic shall be defined
by the description of the cloud service and by the security objectives
and requirements pertaining to assurance level Basic, as defined in
<<annex_a>>, including processes and the software (understood as result
of a development process) underlying the service.

* The evaluation depth for assurance level Basic shall consist solely
of inspection activities, based on a check for completeness and coherence
of the provided documentation on processes and design intended to
confirm the fulfilment of technical and organizational measures, including
requirements for fully automated testing of basic known vulnerabilities
and automated compliance checks by the CSP. A report following defined
procedures shall be generated by the CAB. Self-gathered evidence shall
be regularly submitted to the CAB to justify the continued development
and operation of the service.

* The evaluation depth for assurance level Basic shall be driven by
a predefined audit plan.

As specified in the EUCSA's Article 52(6), assurance level Substantial
is "intended to minimise the known cybersecurity risks, and the risk
of incidents and cyberattacks carried out by actors with limited skills
and resources" and can be further defined as follows:

* Assurance level Substantial should provide reasonable assurance
through evaluation by a CAB that the cloud service is built and operated
with procedures and mechanisms to minimise known cybersecurity risks,
and the risk of incidents and cyberattacks carried out by actors with
limited skills and resources. The CAB shall determine that the cloud
service provider has assessed those risks and implemented suitable
controls that, if operating effectively, minimize those risks and
meet the corresponding security requirements throughout a specified
period.

* Assurance level Substantial should be suitable for cloud services
that are designed to meet typical security requirements on services
for business-critical data and systems.

* The typical attacker profile for assurance level Substantial should
be a small team of persons with hacking abilities and access to a
wide range of known hacking techniques, including social engineering,
but with limited resources, in particular to launch wide attacks or
to discover previously unknown vulnerabilities.

* The evaluation scope for assurance level Substantial shall be defined
by the description of the cloud service and by the security objectives
and requirements pertaining to assurance level Substantial, as defined
in <<annex_a>>, including processes and the software (understood as
result of a development process) underlying the service. The effective
operation of the relevant security controls shall also be demonstrated
throughout a specified period.

* The evaluation scope for assurance level Substantial shall include,
in addition to the requirements for assurance level Basic, on-site
audit including interviews and inspecting samples, plus a verification
that the implementation follows the specified processes and design,
including the validation of the functional tests performed on that
implementation. The security controls for assurance level Substantial
shall include a limited pen testing using known attacks.

As specified in the EUCSA's Article 52(7), assurance level High is
"intended to minimise the risk of state-of-the-art cyberattacks carried
out by actors with significant skills and resources" and can be further
defined as follows:

* Assurance level High should provide reasonable assurance through
evaluation by a CAB that the cloud service is built and operated with
procedures and mechanisms to minimise the risk of state-of- the-art
cyberattacks carried out by actors with significant skills and resources.
The CAB shall determine that the cloud service provider has assessed
those risks and implemented suitable controls that operated effectively
to minimize those risks and meet the corresponding security requirements
throughout a specified period.

* Dedicated requirements are defined in <<annex_a>> to ensure that
controls shall be automatically monitored for continuous operation
in accordance with their design, and that the controls shall be regularly
reviewed and pen tested to validate their actual ability to prevent
or detect security breaches.

* Assurance level High should be suitable for cloud services that
are designed to meet specific (exceeding level 'substantial') security
requirements for mission-critical data and systems.

* The typical attacker profile for assurance level High should be
a team of highly skilled persons with access to significant resources
to design and perform attacks, get insider access, discover or buy
access to previously unknown vulnerabilities.

* The evaluation scope for assurance level High shall be defined by
the description of the cloud service and by the security objectives
and requirements pertaining to assurance level High, as defined in
<<annex_a>>, including processes and the software (understood as result
of a development process) underlying the service. The effective operation
of the relevant security controls shall also be demonstrated throughout
a specified period.

* The evaluation depth for assurance level High shall be based on
the depth for assurance level Substantial, to which requirements on
depth of inspection or testing shall be added to verify that the controls
implemented by the CSP actually meet their objective. In particular,
these requirements concern the automated monitoring of controls and
the review and penetration testing of security controls. Such activities
shall be planned over multiple years, and they shall be performed
by personnel with appropriate competences, in particular when penetration
testing or in-depth technical reviews are required.

* The evaluation depth for assurance level High shall be driven by
a full justification of the coverage for all mappings, including for
processes. It may also include higher expectations for some processes
and their implementation, as defined in the security controls pertaining
to assurance level High.

.RATIONALE
____

*Additional input*

*Article 52 provides details about the assurance levels, and in particular:*

1. A European cybersecurity certification scheme may specify one or
more of the following assurance levels for ICT products, ICT services
and ICT processes: 'basic', 'substantial' or 'high'. The assurance
level shall be commensurate with the level of the risk associated
with the intended use of the ICT product, ICT service or ICT process,
in terms of the probability and impact of an incident.

3. The security requirements corresponding to each assurance level
shall be provided in the relevant European cybersecurity certification
scheme, including the corresponding security functionalities and the
corresponding rigour and depth of the evaluation that the ICT product,
ICT service or ICT process is to undergo.

5. A European cybersecurity certificate or EU statement of conformity
that refers to assurance level 'basic' shall provide assurance that
the ICT products, ICT services and ICT processes for which that certificate
or that EU statement of conformity is issued meet the corresponding
security requirements, including security functionalities, and that
they have been evaluated at a level intended to minimise the known
basic risks of incidents and cyberattacks. The evaluation activities
to be undertaken shall include at least a review of technical documentation.
Where such a review is not appropriate, substitute evaluation activities
with equivalent effect shall be undertaken.

6. A European cybersecurity certificate that refers to assurance level
'substantial' shall provide assurance that the ICT products, ICT services
and ICT processes for which that certificate is issued meet the corresponding
security requirements, including security functionalities, and that
they have been evaluated at a level intended to minimise the known
cybersecurity risks, and the risk of incidents and cyberattacks carried
out by actors with limited skills and resources. The evaluation activities
to be undertaken shall include at least the following: a review to
demonstrate the absence of publicly known vulnerabilities and testing
to demonstrate that the ICT products, ICT services or ICT processes
correctly implement the necessary security functionalities. Where
any such evaluation activities are not appropriate, substitute evaluation
activities with equivalent effect shall be undertaken.

7. A European cybersecurity certificate that refers to assurance level
'high' shall provide assurance that the ICT products, ICT services
and ICT processes for which that certificate is issued meet the corresponding
security requirements, including security functionalities, and that
they have been evaluated at a level intended to minimise the risk
of state-of-the-art cyberattacks carried out by actors with significant
skills and resources. The evaluation activities to be undertaken shall
include at least the following: a review to demonstrate the absence
of publicly known vulnerabilities; testing to demonstrate that the
ICT products, ICT services or ICT processes correctly implement the
necessary security functionalities at the state of the art; and an
assessment of their resistance to skilled attackers, using penetration
testing. Where any such evaluation activities are not appropriate,
substitute activities with equivalent effect shall be undertaken.

Recitals also provide additional information about assurance levels

(65) The assurance level of a European certification scheme is a basis
for confidence that an ICT product, ICT service or ICT process meets
the security requirements of a specific European cybersecurity certification
scheme. In order to ensure the consistency of the European cybersecurity
certification framework, a European cybersecurity certification scheme
should be able to specify assurance levels for European cybersecurity
certificates and EU statements of conformity issued under that scheme.
Each European cybersecurity certificate might refer to one of the
assurance levels: 'basic', 'substantial' or 'high', while the EU statement
of conformity might only refer to the assurance level 'basic'. The
assurance levels would provide the corresponding rigour and depth
of the evaluation of the ICT product, ICT service or ICT process and
would be characterised by reference to technical specifications, standards
and procedures related thereto, including technical controls, the
purpose of which is to mitigate or prevent incidents. Each assurance
level should be consistent among the different sectorial domains where
certification is applied.

(66) A European cybersecurity certification scheme might specify several
evaluation levels depending on the rigour and depth of the evaluation
methodology used. Evaluation levels should correspond to one of the
assurance levels and should be associated with an appropriate combination
of assurance components. For all assurance levels, the ICT product,
ICT service or ICT process should contain a number of secure functions,
as specified by the scheme, which may include: a secure out-of-the-box
configuration, a signed code, secure update and exploit mitigations
and full stack or heap memory protections. Those functions should
have been developed, and be maintained, using security-focused development
approaches and associated tools to ensure that effective software
and hardware mechanisms are reliably incorporated.

(67) For assurance level 'basic', the evaluation should be guided
at least by the following assurance components: the evaluation should
at least include a review of the technical documentation of the ICT
product, ICT service or ICT process by the conformity assessment body.
Where the certification includes ICT processes, the process used to
design, develop and maintain an ICT product or ICT service should
also be subject to the technical review. Where a European cybersecurity
certification scheme provides for a conformity self-assessment, it
should be sufficient that the manufacturer or provider of ICT products,
ICT services or ICT processes has carried out a self-assessment of
the compliance of the ICT product, ICT service or ICT process with
the certification scheme.

(68) For assurance level 'substantial', the evaluation, in addition
to the requirements for assurance level 'basic', should be guided
at least by the verification of the compliance of the security functionalities
of the ICT product, ICT service or ICT process with its technical
documentation.

(69) For assurance level 'high', the evaluation, in addition to the
requirements for assurance level 'substantial', should be guided at
least by an efficiency testing which assesses the resistance of the
security functionalities of ICT product, ICT service or ICT process
against elaborate cyberattacks performed by persons who have significant
skills and resources.
____

*High-level presentation*

All Assurance level defined in the EUCS scheme satisfy all requirements
that are applicable to all EUCSA assurance levels:

* Every assurance level is commensurate with the level of risk associated
to the intended use of the cloud service, as demonstrated in the definition
of suitable services and typical attacker profiles (Article 52(1)).

* Every assurance level defines security requirements and functionalities,
as well as the rigour and depth required in the evaluation (Article
52(3)).

* Every assurance level requires that evaluation activities include
a review of technical documentation (Article 52(5), Recital 67).

* Every assurance level requires a review of the cloud service's main
processes, including the development process used for the development
of the cloud service (Recital 67).

Those are the only requirements defined for assurance level 'basic'
in the EUCSA, which are all satisfied by assurance level Basic.

In addition, assurance level Substantial satisfies the requirements
pertaining to the EUCSA's assurance level 'substantial':

* Assurance level Substantial security controls include a vulnerability
assessment activity that perform a review of publicly known vulnerabilities
(Article 52(6)).

* Assurance level Substantial security controls include a review of
the functional tests of the cloud service's security functionalities
as well as some independent testing requirements (Article 52(6)),

* The assessment methodology for assurance level Substantial mandates
the review of a mapping between the documentation of security functionalities
and their implementation to ensure compliance (Recital 68).

Finally, assurance level High satisfies the requirements pertaining
to the EUCSA's assurance level 'high':

* Assurance level High security controls include a vulnerability assessment
activity that perform a review of publicly known vulnerabilities (Article
52(7)).

* Assurance level High security controls include a review of the functional
tests of the cloud service's security functionalities, as well as
automated monitoring requirements, (Article 52(7)),

* Assurance level High security controls require the use of state-of-the-art
security functionalities (Article 52(7)).

* The assessment methodology for assurance level High mandates the
review of a full mapping between the documentation of security functionalities
and their implementation to ensure compliance (Recital 68).

* The assessment methodology for assurance level High mandates both
design efficiency and operating efficiency to be assessed during the
evaluation (Recital 69). This assessment includes penetration testing
to assess the resistance of security functionalities of the cloud
services (Article 52(7), Recital 69).

Note that, throughout this document, references to the assurance levels
defined in the EUCSA use lowercase and quotes ('basic', 'substantial',
'high'), whereas the assurance levels defined in EUCS are capitalized
(Basic, Substantial, High). The names assigned to assurance levels
in EUCS may be later modified.

=== DETAILED PRESENTATION

This presentation is the full output of the thematic group on assurance
levels, which provides a full background

=== PARAMETERS

==== Intention

The intention provides a general description of the Assurance Level,
most likely matching quite closely the definition from the EU CSA.

==== Suitability

Suitability is about potential restrictions of the types and categories
that may be covered.

==== Attacker profile

The attacker profile cannot be very specific, because of the great
variety of attackers, and it always defines a wide category of attackers.
Typical expected results are as follows:

* The least sophisticated attackers in the range should be stopped,
regardless of their motivation.

* The most sophisticated attackers in the range should be deterred
to attack that particular service. This means that, if they have a
specific reason to attack that particular service, they may succeed
with difficulties, but if they are looking for generic revenue, the
difficulty should encourage them to move to the next target.

Note that this applies as well to the 'high' level. Security certification
cannot provide guarantees against a motivated nation-state determined
to attack a specific site but may discourage them if they are "harvesting"
information.

==== Scope of the Evaluation

In ISO/IEC 15408-3, scope is defined as "the effort is greater because
a larger portion of the IT product is included". This is about gradually
adding elements to be evaluated. The scope of the evaluation should
comprise the service provided by the CSP and clearly identify all
underlying and supporting services and processes.

==== Depth

In ISO/IEC 15408-3, depth is defined as "the effort is greater because
it is deployed to a finer level of design and implementation detail".
This is about considering more and more details and asking more precise
questions. The general principle is to follow an incremental approach,
i.e., that all requirements of a lower level are similarly included
in the depth of the higher level.

==== Rigour

In ISO/IEC 15408-3, a more rigorous assessment is defined as "the
effort is greater because it is applied in a more structured, formal
manner". This is about requiring more structure in the service (for
instance, a security model based on a specific formalism/method) or
adding more structure to the assessment (for instance, requiring a
specific method to collect evidence or provide results).

=== APPLICATION TO ASSURANCE LEVELS

[cols="4",options="unnumbered,header"]
|===
| Level | Basic | Substantial | High

| *Intention*
| Provide limited assurance through a review by an independent third
party that the cloud service is built and operated with procedures
and mechanisms to meet the corresponding security requirements at
a level intended to minimize the known basic risks of incidents and
cyberattacks.
| Provide reasonable assurance through evaluation by an independent
third party that the cloud service is built and operated with procedures
and mechanisms to minimise known cybersecurity risks, and the risk
of incidents and cyberattacks carried out by actors with limited skills
and resources. The CSP has assessed those risks and implemented suitable
controls that, if operating effectively, minimize those risks and
meet the corresponding security requirements throughout a specified
period.
| Provide reasonable assurance through evaluation by an independent
auditor that the cloud service is built and operated with procedures
and mechanisms to minimise the risk of state-of- the- art cyberattacks
carried out by actors with significant skills and resources. The CSP
has assessed those risks and implemented suitable controls that operated
effectively to minimize those risks and meet the corresponding security
requirements throughout a specified period. Security controls are
monitored for continuous operation in accordance with their design;
they are reviewed and pen tested to validate their actual ability
to prevent or detect security breaches.

| *Intention rationale*
| Scope, depth and rigour of the assurance level is limited to procedures
and mechanisms for those security requirements that shall minimize
basis risks only.
| Scope, depth and rigour of this assurance level requires the cloud
service provider to apply a risk-based approach for the suitable design
and implementation of controls that meet the corresponding security
requirements. The systematic risk assessment approach and the operating
effectiveness (consistent application) of controls throughout a specified
period is evaluated by an independent auditor, including for the initial
conformity assessment.
| Scope, depth and rigour of this assurance level extend the previous
level for Substantial by additional procedures to be performed for
automated controls. Automated monitoring is applied by the CSP to
identify exceptions in the application of controls (_e.g._ changes
to the configuration) and initiate corrective actions. Reviews and
pen tests are performed by the independent auditor or a third party
engaged by the CSP with the objective to identify vulnerabilities
that allow to circumvent, override or breach controls.

| *Suitability* 
| The Basic level is suitable for cloud services that are designed
to meet typical security requirements on services for non-critical
data and systems.
| The Substantial level is suitable for cloud services that are designed
to meet typical security requirements on services for business-critical
data and systems.
| The High level is suitable for cloud services that are designed
to meet specific (exceeding level 'substantial') security requirements
for mission critical data and systems.

| *Suitability rationale*
| The 'Basic level provides limited assurance that baseline procedures
and mechanisms are in place to address security risks and threats
in potentially low impact information systems (e.g.: Web site hosting
public information). It is typically not suited for Platform or Infrastructure
capabilities, used by a large number of services. built on top and
that require an elevated level of security. The Basic level demonstrates
a willingness to address security, including the application of security
guidance from subservice providers.
| The Substantial level provides reasonable assurance that a set of
more stringent (than in level Basic) security controls is designed
and operated to address security risks and threats in potentially
moderate impact information systems to protect business critical information
(e.g.: Confidential business data, email, CRM &#8211; customer relation
management systems, personal information). It is suitable for all
capabilities types. . The Substantial level demonstrates a robust
and mature holistic security management to provide secure services.
| The High level provides reasonable assurance that a set of even
more stringent security controls is designed and operated to address
security risks and threats in potentially high impact information
systems to protect mission critical information (e.g. highly confidential
business data, patents).

The costly and rigorous evaluation process reflects the intention
to minimize the risks in using the cloud service.

| *Attacker profile*
| Single person with limited skills repeating a known attack with
limited resources, not including the ability to perform social engineering
attacks.
| Small team of persons with hacking abilities and access to a wide
range of known hacking techniques, including social engineering, but
with limited resources, in particular to launch wide attacks or to
discover previously unknown vulnerabilities.
| Team of highly skilled persons with access to significant resources
to design and perform attacks, get insider attacks, discover or buy
access to previously unknown vulnerabilities.

| *Attacker profile rationale*
| Today, Basic is about removing low-lying fruits and ensuring that
cloud services, including simple ones, are designed with security
in mind. The objective is to remove the possibility to fall victim
to trivial attacks.

When such certification becomes mainstream, the requirements should
be revised upwards.
| This is the "standard" attacker, corresponding to most real-life
attacks used to disclose information, steal resources, deny service,
or tamper with a service.

Their main characteristics come from the definition of the level:
"known attacks" and "limited resources". Note that this definition
is quite ambitious and allows the use of attacks that leverage several
vulnerabilities.
| This is the sophisticated attacker, against which detection and
mitigation is more efficient than resistance. At this level, it may
be difficult to define precisely a way to analyse that the objective
has been met, in particular because there is an expectation to minimize
risks through various mitigation methods.

| *Scope* 
| As defined by the service description and the controls pertaining
to the Basic level, including processes and the software (understood
as result of a development process) underlying the service..
| As defined by the service description and the controls pertaining
to the Substantial level, including processes and the software (understood
as result of a development process) underlying the service.

Operating effectiveness of the controls shall be demonstrated.
| As defined by the service description and the controls pertaining
to the High level, including processes and the software (understood
as result of a development process) underlying the service.

Operating effectiveness of the controls shall be demonstrated. (including
automated monitoring if required by the control definition).

| *Scope rationale*
| This may need to be rephrased, depending on the relationship between
"controls" and "requirements".

Here, the idea would be to include all controls in their general form,
but without the more detailed requirements that may be added for higher
levels.
| We refer to the same controls from the Basic assurance level, but
with the stronger refinements or enhancements (e.g., mandated techniques,
thresholds, _etc_.).

Requirements must include a limited pen testing using known attacks.
| We refer to the same controls from the Substantial assurance level,
but with the higher refinements or enhancements.

Enhancements often included additional constraints, references to
state-of-the-art requirements, and automated monitoring of some controls.

| *Depth* 
| Inspection solely, based on a check for completeness and coherence
of the provided documentation on processes and design intended to
confirm the fulfillment of technical and organizational measures,
and interactions between the auditor and the CSP at the beginning
and at the conclusion of the inspection.

A report following defined procedures is generated by the inspection
body.

Once a year, a documentation update is provided for third- party review
of the continued development and operation of the service.
| Additional to the requirements of Basic: On-site audit including
interviews and inspecting samples, plus a verification that the implementation
follows the specified policies and procedures, and an additional focus
on development activities, for instance on the functional tests performed.

On the initial assessment and once a year, the operating effectiveness
of the security controls, _i.e._ their operation as designed, needs
to be demonstrated over the previous period.
| Additional to the requirements of Substantial: Specific requirements
on the monitoring and testing of the controls, i.e. their operation
as intended to protect from attacks or detect them, needs to be demonstrated.

Different measures may be used, such as technical reviews, and penetration
testing shall be performed by qualified personnel, following a multi-year
plan that needs to be validated in the audit.

| *Depth rationale*
| The inspection focuses on completeness, coherence and plausibility
of the documentation. It needs to be an efficient process that mostly
focuses on the existence of processes, and of a secure by design approach,
to demonstrate the proper design and existence of security measures
to protect the cloud service.
| The full audit aims at providing reasonable assurance that the security
controls are properly designed and operate effectively, _I.e,_ as
designed, over a period of time.
| The audit aims at providing the same reasonable assurance as for
the Substantial level.

The main addition in depth come from additional requirements for level
High, such as automated monitoring and penetration testing, which
are intended to demonstrate that the controls remain effective under
strenuous conditions.

| *Rigour* 
| The assessment is performed by the CSP and driven by a standardised
checklist.

An accredited third-party then audits the assessment report and its
supporting documentation.
| The assessment is performed by an accredited third-party, and it
is driven by a risk analysis performed by the CSP, which is in the
auditscope.
| The assessment is performed as for the Substantial level, but the
CAB needs to be authorized by the NCCA to it has the required competencies
to audit the specific requirements of the High level.

More rigour is expected in the definition and application of policies,
usually as defined in requirements specific to the controls (_e.g._
the need to demonstrate the coverage of functional tests used in development).

| *Rigour rationale*
| The assessment follows all items in a checklist suited to the targeted
cloud service, and its results are reviewed by an accredited third-party.
| A full audit is performed by an independent third-party, and the
checklist approach is replaced by a more rigorous risk-based approach,
allowing the auditor to identify controls that require specific attention.
| The rigour remains mostly the same as for level Substantial, as
it corresponds to typical audit conditions.

Nevertheless, specific requirements explicitly increase the level
of rigour on some controls by requiring additional deliverables from
the CSP.

|===
